name: Continuous Deployment

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*.*'

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
