name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Continuous Integration']
    branches: [master]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download production artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
      - name: Move artifacts to current working directory
        run: |
          mv artifact/* .
          rm -rf artifact
      - name: Upload test coverage
        uses: codecov/codecov-action@v1
      - name: Install dependencies
        run: |
          ls -al
          yarn install --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
